import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "src/components/common/header/Header";
import Footer from "src/components/common/footer/Footer";
import Providers from "src/utils/provider/Providers";
import PlayerBar from "src/components/common/playerBar/PlayerBar";
import { Toaster } from "sonner";
import { GoogleAnalytics } from "@next/third-parties/google";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Providers>
          <Suspense>
            <Header />
          </Suspense>
          <main className="pt-16 bg-gray-50  w-[calc(100vw-8px)] flex-1">
            <Toaster position="bottom-left" richColors />
            {children}
          </main>
          <Footer />
          <PlayerBar />
        </Providers>
      </body>
      <GoogleAnalytics gaId="GTM-K27FMHMH" />
    </html>
  );
}
